name: Daily Bollinger Signal Bot

on:
  # Triggers the workflow at 9:15 AM IST (which is approximately 3:45 AM UTC) every weekday (Monday-Friday)
  schedule:
    - cron: '15 3 * * 1-5'
  # Allows manual running from the Actions tab
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Line 1: Use requirements.txt in the root (this is already likely correct)
          pip install -r requirements.txt 
      
      - name: Run Trading Bot and Send Alerts
        id: scanner
        run: |
          # Line 2: ***CRITICAL CHANGE***
          # We are changing this from 'python app.py' to 'python streamlit_trading_bot.py'
          # to run the signal script instead of the Streamlit web app.
          python streamlit_trading_bot.py
          
      - name: Send Telegram Notification (ONLY if trade_signal is not empty)
        if: ${{ steps.scanner.outputs.signal != '' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            📢 TRADING BOT ALERT: Signal Found
            ------------------------------------
            Signal Details: ${{ steps.scanner.outputs.signal }}
          disable_web_page_preview: true
          
      - name: Complete job
        run: echo "Bot run complete."
