name: Daily Bollinger Signal Bot

# Triggers the workflow at 9:15 AM EST (which is approximately 3:45 AM UTC) every weekday (Monday-Friday)
schedule:
  - cron: '15 3 * * 1-5'

# Allows manual running from the Actions tab
workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # CRITICAL FIX: Use --no-cache-dir to prevent re-using old, broken yfinance versions
          pip install -r requirements.txt --no-cache-dir

      - name: Run Trading Bot and Send Alerts
        id: scanner
        run: |
          # 1. Execute the correct script (app.py) and capture its output into a variable.
          SIGNAL=$(python app.py)
          
          # 2. This critical line saves the variable value to be accessible in the next step.
          echo "SIGNAL_OUTPUT=$SIGNAL" >> $GITHUB_OUTPUT

      - name: Send Telegram Notification (ONLY if trade signal is not empty)
        if: ${{ steps.scanner.outputs.SIGNAL_OUTPUT != '' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            *TRADING BOT ALERT Signal Found*
            Signal Details: ${{ steps.scanner.outputs.SIGNAL_OUTPUT }}
          disable_web_page_preview: true

      - name: Complete Job
        run: echo "Bot run complete."
